### ISSUE TITLE
Doesn't work when a new episode plays automatically

### ISSUE THREAD

**Issue by MaikoHermans** [amet/service.autosubs#40]
I'm currently using nextup service notification which is a supported addon for the rapier skin.

When I play a episode directly from my library the autosubs works just fine however when I let it automatically go to the next episode when the previous episode is over it won't automatically download the subtitles again. I think this might have to with the way the autosubs is being called?

**Comment by schumi2004** [comment]
Should be fixed with https://github.com/amet/service.autosubs/pull/41
